name: Build Netflix App

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: netflix
         tags: 0.0.1
         registry: ghcr.io
         dockerfile: DevSecOps-Project/Dockerfile
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}            